apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockedin-app
  labels:
    app: lockedin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lockedin-app
  template:
    metadata:
      labels:
         app: lockedin-app
    spec:
      containers: 
        - image:  {REPOSITORY}/lockedinsvc:v{BUILD}
          name: lockedin-app
          imagePullPolicy: Always
          ports:
          - name: lockedin-app
            containerPort: 8086
          resources:
            requests:
                cpu: "300m"
                memory: "1850Mi" 
      restartPolicy: Always
      imagePullSecrets:
        - name: rpaacr-secret4
---
kind: Service
apiVersion: v1
metadata:
  name: lockedin-app-svc
spec:
  type: LoadBalancer
  selector:
    app: lockedin-app
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: lockedin-app

