apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockedin
  labels:
    app: lockedin-app
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: lockedin-app
  template:
    metadata:
      labels:
         app: lockedin-app
    spec:
      containers: 
        - image: {REPOSITORY}/xylem_ui_automation:v{BUILD}
          name: xylemuiauto-app
          imagePullPolicy: Always
          ports:
          - name: lockedin-app
            containerPort: 8080
          resources:
            requests:
                cpu: "100m"
                memory: "1500Mi" 
      restartPolicy: Always
      imagePullSecrets:
        - name: rpaacr-secret4
---
kind: Service
apiVersion: v1
metadata:
  name: lockedin-app-svc
spec:
  type: ClusterIP
  selector:
    app: lockedin-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: lockedin-app
